// This file is auto-generated by Wails at build time.
// During development, Wails injects the runtime.
// These stubs are for IDE support only.
export function EventsOn(eventName, callback) { return () => {}; }
export function EventsEmit(eventName, ...data) {}
export function EventsOff(eventName, ...additionalEventNames) {}
export function WindowShow() {}
export function WindowHide() {}
export function WindowMinimise() {}
export function WindowMaximise() {}
export function WindowSetTitle(title) {}
export function Quit() {}
