package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDefaultConfig(t *testing.T) {
	cfg := DefaultConfig()

	if cfg.Hotkey.Binding != "Super+Shift+S" {
		t.Errorf("Hotkey.Binding = %q, want %q", cfg.Hotkey.Binding, "Super+Shift+S")
	}
	if cfg.Hotkey.MeetingBinding != "Super+Shift+X" {
		t.Errorf("Hotkey.MeetingBinding = %q, want %q", cfg.Hotkey.MeetingBinding, "Super+Shift+X")
	}
	if cfg.Audio.Device != "default" {
		t.Errorf("Audio.Device = %q, want %q", cfg.Audio.Device, "default")
	}
	if cfg.Transcription.GPUEnabled {
		t.Error("Transcription.GPUEnabled = true, want false (default)")
	}
	if cfg.Transcription.ModelPath == "" {
		t.Error("Transcription.ModelPath is empty")
	}
	if !cfg.Output.AutoPaste {
		t.Error("Output.AutoPaste = false, want true")
	}
	if !cfg.Output.Clipboard {
		t.Error("Output.Clipboard = false, want true")
	}
	if cfg.Output.SilenceTimeout != 5.0 {
		t.Errorf("Output.SilenceTimeout = %v, want 5.0", cfg.Output.SilenceTimeout)
	}
	// Phase 2 meeting defaults
	if cfg.Meeting.DefaultSources != "both" {
		t.Errorf("Meeting.DefaultSources = %q, want %q", cfg.Meeting.DefaultSources, "both")
	}
	if cfg.Meeting.SpeakerThreshold != 0.65 {
		t.Errorf("Meeting.SpeakerThreshold = %v, want 0.65", cfg.Meeting.SpeakerThreshold)
	}
	if !cfg.Meeting.AutoSave {
		t.Error("Meeting.AutoSave = false, want true")
	}
}

func TestSaveAndLoad(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	original := &Config{
		Hotkey: HotkeyConfig{Binding: "Ctrl+Alt+T"},
		Audio:  AudioConfig{Device: "hw:0,0"},
		Transcription: TranscriptionConfig{
			GPUEnabled: true,
			ModelPath:  "/custom/models",
		},
		Output: OutputConfig{
			AutoPaste:      false,
			Clipboard:      true,
			SilenceTimeout: 3.5,
		},
	}

	if err := Save(original, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	loaded, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}

	if loaded.Hotkey.Binding != original.Hotkey.Binding {
		t.Errorf("Hotkey.Binding = %q, want %q", loaded.Hotkey.Binding, original.Hotkey.Binding)
	}
	if loaded.Audio.Device != original.Audio.Device {
		t.Errorf("Audio.Device = %q, want %q", loaded.Audio.Device, original.Audio.Device)
	}
	if loaded.Transcription.GPUEnabled != original.Transcription.GPUEnabled {
		t.Errorf("Transcription.GPUEnabled = %v, want %v", loaded.Transcription.GPUEnabled, original.Transcription.GPUEnabled)
	}
	if loaded.Transcription.ModelPath != original.Transcription.ModelPath {
		t.Errorf("Transcription.ModelPath = %q, want %q", loaded.Transcription.ModelPath, original.Transcription.ModelPath)
	}
	if loaded.Output.AutoPaste != original.Output.AutoPaste {
		t.Errorf("Output.AutoPaste = %v, want %v", loaded.Output.AutoPaste, original.Output.AutoPaste)
	}
	if loaded.Output.Clipboard != original.Output.Clipboard {
		t.Errorf("Output.Clipboard = %v, want %v", loaded.Output.Clipboard, original.Output.Clipboard)
	}
	if loaded.Output.SilenceTimeout != original.Output.SilenceTimeout {
		t.Errorf("Output.SilenceTimeout = %v, want %v", loaded.Output.SilenceTimeout, original.Output.SilenceTimeout)
	}
}

func TestSaveCreatesDirectories(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "nested", "dirs", "config.toml")

	cfg := DefaultConfig()
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Error("Save() did not create the file")
	}
}

func TestSaveIncludesHeader(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	cfg := DefaultConfig()
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error: %v", err)
	}

	if !strings.HasPrefix(string(data), "# Generated by tomoe auto-init on ") {
		t.Error("Save() output missing header comment")
	}
}

func TestLoadNonexistent(t *testing.T) {
	_, err := Load("/nonexistent/path/config.toml")
	if err == nil {
		t.Error("Load() should return error for nonexistent file")
	}
}

func TestLoadInvalidTOML(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "bad.toml")

	if err := os.WriteFile(path, []byte("not valid [[ toml"), 0o644); err != nil {
		t.Fatalf("WriteFile() error: %v", err)
	}

	_, err := Load(path)
	if err == nil {
		t.Error("Load() should return error for invalid TOML")
	}
}

func TestPathRespectsXDGConfigHome(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", "/custom/config")
	got := Path()
	want := "/custom/config/tomoe/config.toml"
	if got != want {
		t.Errorf("Path() = %q, want %q", got, want)
	}
}

func TestPathDefaultsToHome(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", "")
	got := Path()
	if !strings.HasSuffix(got, filepath.Join(".config", "tomoe", "config.toml")) {
		t.Errorf("Path() = %q, want suffix %q", got, ".config/tomoe/config.toml")
	}
}

func TestModelDirRespectsXDGDataHome(t *testing.T) {
	t.Setenv("XDG_DATA_HOME", "/custom/data")
	got := ModelDir()
	want := "/custom/data/tomoe/models"
	if got != want {
		t.Errorf("ModelDir() = %q, want %q", got, want)
	}
}

func TestModelDirDefaultsToHome(t *testing.T) {
	t.Setenv("XDG_DATA_HOME", "")
	got := ModelDir()
	if !strings.HasSuffix(got, filepath.Join(".local", "share", "tomoe", "models")) {
		t.Errorf("ModelDir() = %q, want suffix %q", got, ".local/share/tomoe/models")
	}
}

func TestBackwardCompatPhase1Config(t *testing.T) {
	// A Phase 1 config (without [meeting] section) should load without error
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	phase1Config := `[hotkey]
binding = "Super+Shift+R"

[audio]
device = "default"

[transcription]
gpu_enabled = true
model_path = "/home/user/.local/share/tomoe/models"

[output]
auto_paste = true
clipboard = true
`
	if err := os.WriteFile(path, []byte(phase1Config), 0o644); err != nil {
		t.Fatalf("WriteFile() error: %v", err)
	}

	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error loading Phase 1 config: %v", err)
	}

	if cfg.Hotkey.Binding != "Super+Shift+R" {
		t.Errorf("Hotkey.Binding = %q, want %q", cfg.Hotkey.Binding, "Super+Shift+R")
	}
	if !cfg.Transcription.GPUEnabled {
		t.Error("GPUEnabled should be true")
	}
	// Meeting section absent from TOML — should get defaults (not zero values)
	if cfg.Meeting.DefaultSources != "both" {
		t.Errorf("Meeting.DefaultSources = %q, want %q (default)", cfg.Meeting.DefaultSources, "both")
	}
	if cfg.Meeting.SpeakerThreshold != 0.65 {
		t.Errorf("Meeting.SpeakerThreshold = %v, want 0.65 (default)", cfg.Meeting.SpeakerThreshold)
	}
	if !cfg.Meeting.AutoDetect {
		t.Error("Meeting.AutoDetect = false, want true (default)")
	}
}

func TestSessionDir(t *testing.T) {
	t.Setenv("XDG_DATA_HOME", "/custom/data")
	got := SessionDir()
	want := "/custom/data/tomoe/sessions"
	if got != want {
		t.Errorf("SessionDir() = %q, want %q", got, want)
	}
}

func TestSilenceTimeoutRoundTrip(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	cfg := DefaultConfig()
	cfg.Output.SilenceTimeout = 7.25

	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	// Verify the TOML file contains the silence_timeout key
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error: %v", err)
	}
	if !strings.Contains(string(data), "silence_timeout") {
		t.Error("saved TOML does not contain silence_timeout key")
	}

	loaded, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if loaded.Output.SilenceTimeout != 7.25 {
		t.Errorf("Output.SilenceTimeout = %v, want 7.25", loaded.Output.SilenceTimeout)
	}
}

func TestSilenceTimeoutZeroRoundTrip(t *testing.T) {
	// SilenceTimeout of 0 means disabled; verify it round-trips correctly
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	cfg := DefaultConfig()
	cfg.Output.SilenceTimeout = 0

	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	loaded, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if loaded.Output.SilenceTimeout != 0 {
		t.Errorf("Output.SilenceTimeout = %v, want 0 (disabled)", loaded.Output.SilenceTimeout)
	}
}

func TestBackwardCompatNoSilenceTimeout(t *testing.T) {
	// A config TOML written before SilenceTimeout was added should parse without error.
	// The SilenceTimeout field should get its zero value (0).
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	oldConfig := `[hotkey]
binding = "Super+Shift+R"

[audio]
device = "default"

[transcription]
gpu_enabled = false
model_path = "/home/user/.local/share/tomoe/models"

[output]
auto_paste = true
clipboard = true
`
	if err := os.WriteFile(path, []byte(oldConfig), 0o644); err != nil {
		t.Fatalf("WriteFile() error: %v", err)
	}

	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}

	// Existing fields should parse correctly
	if !cfg.Output.AutoPaste {
		t.Error("Output.AutoPaste = false, want true")
	}
	if !cfg.Output.Clipboard {
		t.Error("Output.Clipboard = false, want true")
	}
	// SilenceTimeout absent from TOML — should get default (not zero)
	if cfg.Output.SilenceTimeout != 5.0 {
		t.Errorf("Output.SilenceTimeout = %v, want 5.0 (default)", cfg.Output.SilenceTimeout)
	}
}

// TestDefaultCalendarConfig covers the Calendar section's factory defaults
// so a config written before this section shipped continues to behave as
// before.
func TestDefaultCalendarConfig(t *testing.T) {
	cfg := DefaultConfig()
	if cfg.Calendar.Enabled {
		t.Error("Calendar.Enabled = true, want false (off by default)")
	}
	if cfg.Calendar.MatchStartWindowMinutes != 15 {
		t.Errorf("MatchStartWindowMinutes = %d, want 15", cfg.Calendar.MatchStartWindowMinutes)
	}
	if cfg.Calendar.MatchEndWindowBound {
		t.Error("MatchEndWindowBound = true, want false (unbounded)")
	}
	if cfg.Calendar.MatchScoreThreshold != 40 {
		t.Errorf("MatchScoreThreshold = %d, want 40", cfg.Calendar.MatchScoreThreshold)
	}
	if cfg.Calendar.CacheTTLSeconds != 300 {
		t.Errorf("CacheTTLSeconds = %d, want 300", cfg.Calendar.CacheTTLSeconds)
	}
	if cfg.Calendar.Jev.Enabled {
		t.Error("Jev.Enabled = true, want false")
	}
	if cfg.Calendar.Jev.TopicWeight != 40 {
		t.Errorf("Jev.TopicWeight = %d, want 40", cfg.Calendar.Jev.TopicWeight)
	}
	if cfg.Calendar.Jev.TranscriptContextSeconds != 120 {
		t.Errorf("Jev.TranscriptContextSeconds = %d, want 120", cfg.Calendar.Jev.TranscriptContextSeconds)
	}
}

// TestICSAutoEnable covers the ergonomic shortcut: enabled=true + ICS
// entries + no explicit providers list should behave as providers=["ical"].
func TestICSAutoEnable(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	body := `[calendar]
enabled = true

[[calendar.ical]]
name = "Personal"
url = "https://calendar.example.com/basic.ics"
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(cfg.Calendar.Providers) != 1 || cfg.Calendar.Providers[0] != "ical" {
		t.Errorf("Providers = %v, want [ical] (auto-enable)", cfg.Calendar.Providers)
	}
	if len(cfg.Calendar.ICal) != 1 || cfg.Calendar.ICal[0].Name != "Personal" {
		t.Errorf("ICal = %+v, want one Personal entry", cfg.Calendar.ICal)
	}
}

// TestICSAutoEnableRespectsExplicitProviders covers the case where the user
// has explicitly written providers=[...]. Auto-enable must not clobber it.
func TestICSAutoEnableRespectsExplicitProviders(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	body := `[calendar]
enabled = true
providers = ["ical", "google"]

[[calendar.ical]]
name = "Personal"
url = "https://example.com/basic.ics"
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if len(cfg.Calendar.Providers) != 2 || cfg.Calendar.Providers[0] != "ical" || cfg.Calendar.Providers[1] != "google" {
		t.Errorf("Providers = %v, want explicit list preserved", cfg.Calendar.Providers)
	}
}

// TestICSAutoEnableSkipsWhenDisabled covers the case where the user has ICS
// entries but hasn't enabled calendar. Providers stays empty; nothing runs.
func TestICSAutoEnableSkipsWhenDisabled(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	body := `[[calendar.ical]]
name = "Personal"
url = "https://example.com/basic.ics"
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.Calendar.Enabled {
		t.Error("Calendar.Enabled = true, want false")
	}
	if len(cfg.Calendar.Providers) != 0 {
		t.Errorf("Providers = %v, want empty (calendar off)", cfg.Calendar.Providers)
	}
}

// TestJevAPIKeyExpansion covers the config-expansion synergy: an operator
// pastes $(pass show ...) into the Jev API key and Load resolves it.
func TestJevAPIKeyExpansion(t *testing.T) {
	t.Setenv("TOMOE_TEST_JEV_KEY", "resolved-jev-key")

	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	body := `[calendar.jev]
enabled = true
api_key = "${TOMOE_TEST_JEV_KEY}"
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	cfg, err := Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if cfg.Calendar.Jev.APIKey != "resolved-jev-key" {
		t.Errorf("Jev.APIKey = %q, want %q", cfg.Calendar.Jev.APIKey, "resolved-jev-key")
	}
}

func TestExistsWhenFilePresent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "tomoe", "config.toml")

	t.Setenv("XDG_CONFIG_HOME", dir)

	if Exists() {
		t.Error("Exists() = true before config file is created")
	}

	cfg := DefaultConfig()
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	if !Exists() {
		t.Error("Exists() = false after config file is created")
	}
}
