package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDefaultConfig(t *testing.T) {
	cfg := DefaultConfig()

	if cfg.Hotkey.Binding != "Super+Shift+R" {
		t.Errorf("Hotkey.Binding = %q, want %q", cfg.Hotkey.Binding, "Super+Shift+R")
	}
	if cfg.Audio.Device != "default" {
		t.Errorf("Audio.Device = %q, want %q", cfg.Audio.Device, "default")
	}
	if cfg.Transcription.GPUEnabled {
		t.Error("Transcription.GPUEnabled = true, want false (default)")
	}
	if cfg.Transcription.ModelPath == "" {
		t.Error("Transcription.ModelPath is empty")
	}
	if !cfg.Output.AutoPaste {
		t.Error("Output.AutoPaste = false, want true")
	}
	if !cfg.Output.Clipboard {
		t.Error("Output.Clipboard = false, want true")
	}
}

func TestSaveAndLoad(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	original := &Config{
		Hotkey: HotkeyConfig{Binding: "Ctrl+Alt+T"},
		Audio:  AudioConfig{Device: "hw:0,0"},
		Transcription: TranscriptionConfig{
			GPUEnabled: true,
			ModelPath:  "/custom/models",
		},
		Output: OutputConfig{
			AutoPaste: false,
			Clipboard: true,
		},
	}

	if err := Save(original, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	loaded, err := Load(path)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}

	if loaded.Hotkey.Binding != original.Hotkey.Binding {
		t.Errorf("Hotkey.Binding = %q, want %q", loaded.Hotkey.Binding, original.Hotkey.Binding)
	}
	if loaded.Audio.Device != original.Audio.Device {
		t.Errorf("Audio.Device = %q, want %q", loaded.Audio.Device, original.Audio.Device)
	}
	if loaded.Transcription.GPUEnabled != original.Transcription.GPUEnabled {
		t.Errorf("Transcription.GPUEnabled = %v, want %v", loaded.Transcription.GPUEnabled, original.Transcription.GPUEnabled)
	}
	if loaded.Transcription.ModelPath != original.Transcription.ModelPath {
		t.Errorf("Transcription.ModelPath = %q, want %q", loaded.Transcription.ModelPath, original.Transcription.ModelPath)
	}
	if loaded.Output.AutoPaste != original.Output.AutoPaste {
		t.Errorf("Output.AutoPaste = %v, want %v", loaded.Output.AutoPaste, original.Output.AutoPaste)
	}
	if loaded.Output.Clipboard != original.Output.Clipboard {
		t.Errorf("Output.Clipboard = %v, want %v", loaded.Output.Clipboard, original.Output.Clipboard)
	}
}

func TestSaveCreatesDirectories(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "nested", "dirs", "config.toml")

	cfg := DefaultConfig()
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Error("Save() did not create the file")
	}
}

func TestSaveIncludesHeader(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "config.toml")

	cfg := DefaultConfig()
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile() error: %v", err)
	}

	if !strings.HasPrefix(string(data), "# Generated by tomoe auto-init on ") {
		t.Error("Save() output missing header comment")
	}
}

func TestLoadNonexistent(t *testing.T) {
	_, err := Load("/nonexistent/path/config.toml")
	if err == nil {
		t.Error("Load() should return error for nonexistent file")
	}
}

func TestLoadInvalidTOML(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "bad.toml")

	if err := os.WriteFile(path, []byte("not valid [[ toml"), 0o644); err != nil {
		t.Fatalf("WriteFile() error: %v", err)
	}

	_, err := Load(path)
	if err == nil {
		t.Error("Load() should return error for invalid TOML")
	}
}

func TestPathRespectsXDGConfigHome(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", "/custom/config")
	got := Path()
	want := "/custom/config/tomoe/config.toml"
	if got != want {
		t.Errorf("Path() = %q, want %q", got, want)
	}
}

func TestPathDefaultsToHome(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", "")
	got := Path()
	if !strings.HasSuffix(got, filepath.Join(".config", "tomoe", "config.toml")) {
		t.Errorf("Path() = %q, want suffix %q", got, ".config/tomoe/config.toml")
	}
}

func TestModelDirRespectsXDGDataHome(t *testing.T) {
	t.Setenv("XDG_DATA_HOME", "/custom/data")
	got := ModelDir()
	want := "/custom/data/tomoe/models"
	if got != want {
		t.Errorf("ModelDir() = %q, want %q", got, want)
	}
}

func TestModelDirDefaultsToHome(t *testing.T) {
	t.Setenv("XDG_DATA_HOME", "")
	got := ModelDir()
	if !strings.HasSuffix(got, filepath.Join(".local", "share", "tomoe", "models")) {
		t.Errorf("ModelDir() = %q, want suffix %q", got, ".local/share/tomoe/models")
	}
}

func TestExistsWhenFilePresent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "tomoe", "config.toml")

	t.Setenv("XDG_CONFIG_HOME", dir)

	if Exists() {
		t.Error("Exists() = true before config file is created")
	}

	cfg := DefaultConfig()
	if err := Save(cfg, path); err != nil {
		t.Fatalf("Save() error: %v", err)
	}

	if !Exists() {
		t.Error("Exists() = false after config file is created")
	}
}
